### ISSUE TITLE
Debt Wall

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#1]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Sunday Jul 08, 2018 at 21:48 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/1_

----

A dumping ground for improvements as I leave technical debt everywhere :shit: :

- [ ] Configuration Transforms has an `additional transforms` filed which needs to be added to the provider

- [ ] `step_start_trigger` should be a `bool`

- [ ] `skip_machine_behavior` should be a `bool` and the property name changed, as there is only two options: `SkipUnavailableMachines` or `None`

- [ ] There should be two more deployment step blocks inside a project, `IIS Virtual Directory` and `IIS Web Application`. The struct for these values are in [this gist](https://gist.github.com/MattHodge/b061ce77d39210ac552e8a8c0c43a5b4)

- [ ] `application_pool_identity` is missing a `SpecificUser` option which is blocked by to https://github.com/MattHodge/go-octopusdeploy/issues/8

- [ ] Deployment step ordering is currently not working correctly

**Comment by AdminTurnedDevOps** [comment]
Closing this as we'll find a more organized approach for technical debt recordings.
