### ISSUE TITLE
User resource missing

### ISSUE THREAD

**Issue by MJRichardson** [OctopusDeploy/terraform-provider-octopusdeploy#101]
The [User-Creation example](https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/examples/User-Creation/main.tf) suggests that users can be created, but executing it gives 

```
The provider provider.octopusdeploy does not support resource type
"octopusdeploy_user"
```

(and I can't find any trace of it in the provider code)

**Comment by rwkarg** [comment]
`beta-candidate-01` is the active branch and User resources are updated there. Specifically, there are individual resources for the different types of users:
https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/tree/beta-candidate-01/examples

Also note that Token users are not yet included in that branch, but many others are: https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/issues/93

**Comment by jbristowe** [comment]
Every account type is now supported in the `beta-candidate-01` branch. This branch will soon be merged into our main branch and a release will be produced.
