### ISSUE TITLE
Add variable in variableset resource

### ISSUE THREAD

**Issue by janlud** [OctopusDeploy/terraform-provider-octopusdeploy#105]
Hi,

We would like to create variables in variable set. I can see the variable set resource, but no way to create variable in the set.
Is there a way or the resource is missing?

Thanks!

**Comment by jbristowe** [comment]
Hey @janlud! 👋 

I've added support for variables in variable sets in the `beta-candidate-01` branch. Please give it a try!

**Comment by jan-ludvik-deltatre** [comment]
Hi, @jbristowe, apologies but we haven't tested it yet. However we did start using the provider from TF registry - which is great, thanks! I wanted to ask - is this change now merged or still on the branch?

**Comment by daniel-pleskac-deltatre** [comment]
Hi @jbristowe, thanks for working on this feature. Do you plan to release it? It'd be greatly appreciated.
