### ISSUE TITLE
Tests are not passed. 

### ISSUE THREAD

**Issue by fqjony** [OctopusDeploy/terraform-provider-octopusdeploy#108]
**Describe the bug**
I'm trying to build own build and deploy logic for the forked repository, but I'm not able to pass tests successfully from `master` branch. 

**Steps to reproduce**

**!Important**: All the provided steps were done locally. 

1. Clone repository locally and checkout to `master` branch.
2. Export ENVs https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/.github/workflows/test.yml#L12-L13.
3. Start Octopus containers https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/.github/workflows/test.yml#L20-L21
4. Generate Octopus API key https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/.github/workflows/test.yml#L23-L25
5. Export Octopus API key to ENV.
6. Build the provider https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/.github/workflows/test.yml#L27-L28
7. Enable `TF_ACC` env.
8. Run tests https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/.github/workflows/test.yml#L30-L31 

**Expected behavior**
All tests passed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12067297/99382654-82a61680-28d5-11eb-99d7-0314e5122273.png)
![image](https://user-images.githubusercontent.com/12067297/99382693-92255f80-28d5-11eb-9285-489e4ea8c5eb.png)
![image](https://user-images.githubusercontent.com/12067297/99382730-9ea9b800-28d5-11eb-940f-6be9583c9f9a.png)
![image](https://user-images.githubusercontent.com/12067297/99382769-acf7d400-28d5-11eb-8b22-8cb10874827b.png)

**Environment and versions:**
![image](https://user-images.githubusercontent.com/12067297/99383894-3fe53e00-28d7-11eb-9e8d-5196c049f749.png)

**Comment by jbristowe** [comment]
Hey @fqjony! 👋 

You're correct: the tests are currently broken. I'm working on getting these fixed. Also, active work is being done in the `beta-candidate-01` branch. This will be merged (soon) with `master`.

**Comment by fqjony** [comment]
That makes sense. Looking forward to the updates.
Thanks, @jbristowe.

**Comment by jbristowe** [comment]
Tests are now enabled via `TF_ACC`. Now resolving tests.

**Comment by jbristowe** [comment]
All tests now pass.
