### ISSUE TITLE
Add Azure Account support

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#11]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [droyad](https://github.com/droyad)**
_Sunday Dec 09, 2018 at 23:24 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/27_

----

[AzureSubscriptionAccount](https://github.com/OctopusDeploy/OctopusClients/blob/db7f859c0e8370a96b59a9d19820410981194bb9/source/Octopus.Client/Model/Accounts/AzureSubscriptionAccountResource.cs) and AzureServicePrincipalAccountResource

**Comment by AdminTurnedDevOps** [comment]
Azure accounts are now supported via the beta.
