### ISSUE TITLE
Feed data source is not capturing id

### ISSUE THREAD

**Issue by acraven** [OctopusDeploy/terraform-provider-octopusdeploy#115]
**Describe the bug**
It is not possible to use the id property of the Feed data source as it returns a date causing the apply phase to error.

**Expected behavior**
I would expect `data.octopusdeploy_feeds.docker_hub.id` to return `Feeds-1001` (in this case) and the apply to succeed.

**Steps to reproduce**
This is an extract from my Terraform config (if I use the literal `feed_id` then the apply phase works as expected):
```
data "octopusdeploy_feeds" "docker_hub" {
  partial_name = digitalocean_kubernetes_cluster.default.name
  feed_type    = "Docker"
}

resource "octopusdeploy_kubernetes_cluster_deployment_target" "default" {
   ...
  container {
    feed_id = data.octopusdeploy_feeds.docker_hub.id # TODO renders a date
    # feed_id = "Feeds-1001"
    image   = "octopusdeploy/worker-tools:2.0.1-ubuntu.18.04"
  }
}
```

**Logs and other supporting information**
This is an extract from my remote state following an apply using a literal `feed_id = "Feeds-1001"` rather than the data source:
```
   {
      "mode": "data",
      "type": "octopusdeploy_feeds",
      "name": "docker_hub",
      "provider": "provider[\"terraform.concilify.com/concilify/octopusdeploy\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "feed_type": "Docker",
            "feeds": null,
            "id": "Feeds 2020-12-14 19:05:56.520483626 +0000 UTC",
            "ids": null,
            "partial_name": "test-kubernetes",
            "skip": null,
            "take": 1
          },
          "sensitive_attributes": []
        }
      ]
    }
```

**Environment and versions:**

Terraform Cloud: 0.14.2
Octopus Terraform Provider Version: personal build of beta-candidate-01

**Comment by jbristowe** [comment]
Data sources represent a read-only collection of items for the current state based on the query you provide. Here, `octopusdeploy_feeds` has a collection of `feed` items. I use a timestamped `id` value to reflect when this collection was last created/modified.

To get the `id` value of individual `feed` items, you'll have to reference the index of the collection. For example:

```terraform
data "octopusdeploy_feeds" "docker_hub" {
  partial_name = digitalocean_kubernetes_cluster.default.name
  feed_type    = "Docker"
}

resource "octopusdeploy_kubernetes_cluster_deployment_target" "default" {
   ...
  container {
    feed_id = data.octopusdeploy_feeds.docker_hub[0].id # use the first item
    # feed_id = "Feeds-1001"
    image   = "octopusdeploy/worker-tools:2.0.1-ubuntu.18.04"
  }
}
```

**Comment by acraven** [comment]
Thanks @jbristowe I can definitely use that - I hadn't fully appreciated the move to filter/collection semantics.

The solution makes sense, but I wonder if this isn't a good use case for a singular `octopusdeploy_feed` data source that has a `name` filter for an exact match and would return the id via `data.octopusdeploy_feed.docker_hub.id`.

I'm interested to know the reasoning behind the move to filter/collection semantics? I find the singular data sources (outside Octopus too) convenient for a lookup where I have a name and I'm expecting 1 and only 1 match.

I worry that where I use a partial name there may come a time where the result contains a different item for index 0.

**Comment by acraven** [comment]
Unfortunately the `feeds[0].id` suggestion doesn't work for me. I have a feed with a name `DockerHub` and neither `ids`, `name` nor `partial_name` can identify it. I'm also struggling with `project[0].id` too.

The schema between the two appears inconsistent - `feeds` is plural, `project` is singular, but the data reader in both cases refers to the singular:
`d.Set("feed", flattenedFeeds)`
`d.Set("project", flattenedProjects)`

**Comment by jbristowe** [comment]
This was a bug. I've ensured that every data source now sets a plural form (i.e. `feeds`).

```terraform
data "octopusdeploy_feeds" "feeds" {
  take = 10
}
```

This will return a collection of `feeds` with a maximum of 10 items. Alternatively, you can specify a `partial_name` filter:

```terraform
data "octopusdeploy_feeds" "feeds" {
  partial_name = "DockerHub"
}
```

The underlying API that's targeted doesn't have a query for name matching. It does (however) have a partial name matching operation (i.e. `"/api/feeds{/id}{?skip,take,ids,partialName,feedType}"`).

**Comment by acraven** [comment]
Thanks for the fix. I can confirm that `octopusdeploy_feeds` and `data.octopusdeploy_feeds.docker_hub.feeds[0].id` are now working. I'm not having any luck with the `octopusdeploy_projects` though.

Using the API `/api/Spaces-1/projects?partialName=api&take=1` returns 1 item as expected as follows:

```
{
    "ItemType": "Project",
    "TotalResults": 1,
...
    "Items": [
        {
            "Id": "Projects-1",
            "VariableSetId": "variableset-Projects-1",
...
            "SpaceId": "Spaces-1",
            "ExtensionSettings": [],
            "Name": "api",
            "Slug": "api",
            "Description": "",
...
```

The plan phase fails as follows:
```
Error: Attempt to index null value

  on 17.octopusdeploy-variables.concilify.tf line 36, in resource "octopusdeploy_variable" "default":
  36:   project_id = data.octopusdeploy_projects.api.projects[0].id
    |----------------
    | data.octopusdeploy_projects.api.projects is null
```

Using a literal for `project_id` allows the plan and apply phases to complete. The state then shows the following empty projects:
```
    {
      "mode": "data",
      "type": "octopusdeploy_projects",
      "name": "api",
      "provider": "provider[\"terraform.concilify.com/concilify/octopusdeploy\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cloned_from_project_id": null,
            "id": "Projects 2020-12-15 23:31:16.739160293 +0000 UTC",
            "ids": null,
            "is_clone": null,
            "name": null,
            "partial_name": "api",
            "projects": null,
            "skip": null,
            "take": 1
          },
          "sensitive_attributes": []
        }
      ]
    },
```

**Comment by jbristowe** [comment]
Your configuration should look something like this:

```terraform
data "octopusdeploy_projects" "api" {
  partial_name = "api"
}
```

You can then reference the ID value through `data.octopusdeploy_projects.api.projects[0].id`.

**Comment by jbristowe** [comment]
There was a bug processing `project` elements if release versioning was based on a package. This has been fixed. You should be able to reference items in the returning collection.

**Comment by acraven** [comment]
Thanks very much. I can confirm that both the feeds and projects data sources are now working for me.
