### ISSUE TITLE
Add Docker Feed 

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#12]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [droyad](https://github.com/droyad)**
_Sunday Dec 09, 2018 at 23:28 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/28_

----

https://github.com/OctopusDeploy/OctopusClients/blob/db7f859c0e8370a96b59a9d19820410981194bb9/source/Octopus.Client/Model/DockerFeedResource.cs

**Comment by AdminTurnedDevOps** [comment]
Docker feed is now available for the beta through the `feed` resource.
