### ISSUE TITLE
Cannot get endpoints from server

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#14]
<a href="https://github.com/jjjurrb"><img src="https://avatars0.githubusercontent.com/u/28757446?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjjurrb](https://github.com/jjjurrb)**
_Saturday Feb 02, 2019 at 19:08 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/37_

----

Hi,

I'm testing out the provider by setting up some variables and getting and error when running `terraform plan`, init completes successfully,

```
Error: Error refreshing state: 2 error(s) occurred:

* data.octopusdeploy_environment.octoterratest: 1 error(s) occurred:

* data.octopusdeploy_environment.octoterratest: data.octopusdeploy_environment.octoterratest: error reading environment with name OctoTerraTest: cannot get endpoint environments from server. failure from http client invalid character '<' looking for beginning of value
* data.octopusdeploy_project.octoterra: 1 error(s) occurred:

* data.octopusdeploy_project.octoterra: data.octopusdeploy_project.octoterra: error reading project name OctoTerra: cannot get endpoint projects from server. failure from http client invalid character '<' looking for beginning of value
```
I can query the project via the API ok.  Running Octopus 2018.10.1

My config:
`00-config.tf`
```
terraform {
  backend "local" {
    path = "state/terraform.tfstate"
  }
}
provider "octopusdeploy" {
  address = "http://octopus.local"
  apikey  = "${file("/mnt/c/Temp/ocotpus-api-key")}"
}
```
`05-main.tf`
```
data "octopusdeploy_project" "octoterra" {
    name = "OctoTerra"
}
 data "octopusdeploy_environment" "octoterratest" {
     name = "OctoTerraTest"
 }

 resource "octopusdeploy_variable" "connection_string" {
  project_id = "${data.octopusdeploy_project.octoterra.id}"
  name       = "SomeConnectionString"
  type       = "String"
  value      = "Server=someSQLServer;Database=someDatabase;Trusted_Connection=True;"

  scope {
    environments = ["${data.octopusdeploy_environment.octoterratest.id}"]
  }
 }
```
Thanks

**Comment by MattHodge** [comment]
<a href="https://github.com/jjjurrb"><img src="https://avatars0.githubusercontent.com/u/28757446?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jjjurrb](https://github.com/jjjurrb)**
_Saturday Feb 02, 2019 at 20:13 GMT_

----

Error has changed.  I now have the same error that has been logged here: https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/6
```
* data.octopusdeploy_project.octoterra: data.octopusdeploy_project.octoterra: error reading project name OctoTerra: cannot get endpoint projects from server. failure from http client json: cannot unmarshal string into Go struct field ActionTemplateParameter.DefaultValue of type map[string]octopusdeploy.PropertyValue
```
Did that ever get resolved?  Thanks.

**Comment by jeff-french** [comment]
JSON marshalling was resolved in the underlying library. Closing this. Feel free to re-open if the issue still occurs.
