### ISSUE TITLE
Package references incorrectly set the extract option as numbers instead of booleans

### ISSUE THREAD

**Issue by michaelnoonan** [OctopusDeploy/terraform-provider-octopusdeploy#29]
**Describe the bug**
I'm trying to configure some package references using the Octopus Terraform provider and I think there is a bug with setting the extract during deployment option.

Instead of correctly setting the option to `True` or `False`, it's coming through as `0` or `1`. This is not enabling the option successfully.

**Steps to reproduce**
This is the Terraform configuration I'm using:

```
package {
name = "Server.Shipping"
package_id = "Server.Shipping"
feed_id = "feeds-builtin"
acquisition_location = "NotAcquired"
extract_during_deployment = true
}


package {
name = "MyPackage"
package_id = "MyPackage"
feed_id = "feeds-builtin"
acquisition_location = "NotAcquired"
extract_during_deployment = false
}
```

Which results in the correct package references, but the extract option is set to `0` or `1` which doesn't work as expected.

**Expected behavior**
I expected the values for the extract option to be `True` or `False` and for the deployment process to extract the packages as configured.

**Logs and other supporting information**
Add the output of running `tf plan` or `tf apply` along with any errors in the Octopus Server logs.

**Screenshots**

**Environment and versions:**
- OS: [e.g. `Windows`, `Linux`, `OSX`]
- Octopus Server Version: [e.g. `2019.6.1`]
- Terraform Version: [e.g. `0.12.4`]
- Octopus Terraform Provider Version: [e.g. `0.2.0`]

**Additional context**
Discussed in this private conversation: https://secure.helpscout.net/conversation/901044663/47109/

**Comment by nemitche** [comment]
While trying to capture a plan output the provider seems to have gotten into an odd state with the packages.

Both have the Extract option set to True in Octopus, and I modified the Terraform configuration to set both to true as well.

After running a refresh, followed by a plan, I get the following output:

Terraform will perform the following actions:

  ~ octopusdeploy_deployment_process.athena_game_server_ga_playfab_upload
      step.8.action.0.package.1806912532.acquisition_location:      "NotAcquired" => "NotAcquired"
      step.8.action.0.package.1806912532.extract_during_deployment: "1" => "1"
      step.8.action.0.package.1806912532.feed_id:                   "feeds-builtin" => "feeds-builtin"
      step.8.action.0.package.1806912532.name:                      "Server.Shipping" => "Server.Shipping"
      step.8.action.0.package.1806912532.package_id:                "Server.Shipping" => "Server.Shipping"
      step.8.action.0.package.1806912532.property.#:                "0" => "0"
      step.8.action.0.package.3381256853.acquisition_location:      "" => "NotAcquired"
      step.8.action.0.package.3381256853.extract_during_deployment: "" => "1"
      step.8.action.0.package.3381256853.feed_id:                   "" => "feeds-builtin"
      step.8.action.0.package.3381256853.name:                      "" => "MyPackage"
      step.8.action.0.package.3381256853.package_id:                "" => "MyPackage"
      step.8.action.0.package.3381256853.property.#:                "0" => "0"
      step.8.action.0.package.875230384.acquisition_location:       "NotAcquired" => ""
      step.8.action.0.package.875230384.extract_during_deployment:  "0" => ""
      step.8.action.0.package.875230384.feed_id:                    "feeds-builtin" => ""
      step.8.action.0.package.875230384.name:                       "MyPackage" => ""
      step.8.action.0.package.875230384.package_id:                 "MyPackage" => ""
      step.8.action.0.package.875230384.property.#:                 "0" => "0"

You can see the option coming through as 0 or 1. For some reason, it's also moving the MyPackage reference to a new id.

OS: Windows
Octopus Server Version: v2019.3.3  LTS
Terraform Version: 0.11.14
Octopus Terraform Provider Version: 0.2.0

**Comment by droyad** [comment]
`extract_during_deployment` is a bindable field, so it should be treated as a string

**Comment by nemitche** [comment]
Thanks a lot, changing the values to strings allowed them to come through successfully.

**Comment by droyad** [comment]
Ah nice! In the schema we [define it as a string](https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/9aee82113d4ab08babf244775a15ed48a4f5ae19/octopusdeploy/package_reference.go#L27), interesting the Terraform validation allowed a boolean.

It does kind of make sense to allow booleans, we might just need to test for them and convert them properly.

**Comment by nemitche** [comment]
Sounds like a good idea.

Although the package reference was set up correctly, Octopus itself still seemed to have a problem when running a deploy because it failed to acquire the package. I had to open the package reference and resaved it to get it working.

This might be related to another bug about steps based on templates not inheriting packages correctly when created through the API: https://github.com/OctopusDeploy/Issues/issues/5649

**Comment by AdminTurnedDevOps** [comment]
FYI - This is directly related to `package_reference.go`. 

We will put this on our list to continue looking into. Thank you.
