### ISSUE TITLE
Azure machine target communication options missing

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#3]
<a href="https://github.com/laurencee"><img src="https://avatars1.githubusercontent.com/u/3850553?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [laurencee](https://github.com/laurencee)**
_Saturday Oct 27, 2018 at 11:43 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/10_

----

Heya,

First off I just want to say that this provider looks amazing and I think will solve a lot of problems with managing octopus resources in the future.

In my case, I'm looking to manage some AzureWebApp machine targets but unfortunately that's not possible as the current state of this provider doesn't have the ability to pass through the account and web app name as part of the communication method.

The resource arguments for machine targets might need a bit of a refactor as there are different required sets of communication options for the different targets. I think it could look something along these lines:

For a tentacle
```
endpoint {
  communicationstyle = "TentaclePassive"
  tentacle_config {
    thumbprint         = "81D0FF8B76FC"
    uri                = "https://finance-web-01:10933"
  }
}
```

For an AzureWebApp
```
endpoint {
  communicationstyle = "AzureWebApp"
  azure_web_app_config {
    account         = "SomeAzureAccount"
    web_app        = "web-app-reference"
    web_app_slot = "optional-slot"
  }
}
```

(I'm not sure how the api exposes the account/webapp settings, might need to be reference ids or something)

etc.

**Comment by AdminTurnedDevOps** [comment]
Thank you. We'll add this into the features list for V2.
