### ISSUE TITLE
octopusdeploy_variable breaks if you specify scope.tenant_tags

### ISSUE THREAD

**Issue by SethNute** [OctopusDeploy/terraform-provider-octopusdeploy#33]
**Describe the bug**
Creating an octopus variable using the `octopusdeploy_variable` causes a problem if you specify a value for `scope.tenant_tags`. The `terraform apply` command errors out with `Error: TenantTag is not a supported scope for variable matching`. However, the variable is actually created correctly in Octopus.

**Steps to reproduce**
1. In `main.tf`
```
data "octopusdeploy_environment" "test" {
  name = "test"
}

resource "octopusdeploy_variable" "test" {
  project_id    = "Projects-1"
  name          = "FakeName"
  type          = "String"
  value         = "FakeValue"
  
  scope {
    environments = [
      data.octopusdeploy_environment.current.id
    ]
    tenant_tags = [
      "TagCategory/TagName"
    ]
  }
}
```
2. `terraform apply -target="octopusdeploy_variable.test"`
3. See error in console
4. Go to the project corresponding to `Project-1` in Octopus, notice that the variable was actually created correctly even though Terraform exited
5. `terraform state list` note that the `octopusdeploy_variable.test` resource was not added to Terraform`s state

**Expected behavior**
The `octopusdeploy_variable` resource is correctly added to Terraform's state and doesn't cause Terraform to exit.

**Logs and other supporting information**
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # octopusdeploy_variable.test will be created
  + resource "octopusdeploy_variable" "test" {
      + id         = (known after apply)
      + name       = "FakeName"
      + project_id = "Projects-1"
      + type       = "String"
      + value      = "FakeValue"

      + scope {
          + actions      = []
          + channels     = []
          + environments = [
              + "Environments-1",
            ]
          + machines     = []
          + roles        = []
          + tenant_tags  = [
              + "TagCategory/TagName",
            ]
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "myworkspace"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

octopusdeploy_variable.test: Creating...

Error: TenantTag is not a supported scope for variable matching

  on main.tf line 867, in resource "octopusdeploy_variable" "test":
 867: resource "octopusdeploy_variable" "test" {
```

**Screenshots**
N/A

**Environment and versions:**
- OS: Windows 10 Enterprise 1809
- Octopus Server Version: 2019.6.3 LTS
- Terraform Version: 0.12.6
- Octopus Terraform Provider Version: 0.4.0

**Additional context**
If you `terraform import` a octopusdeploy_variable with a tenant tag scope the next `terraform apply` you do will fail with the error: `unable to locate variable in project Projects-1`
Perhaps having tenant tags as variable scopes wasn't available in an earlier Octopus version? The exact error message I am seeing seems to come from here, where tenant tags are purposely excluded  from variable matching via scope: https://github.com/MattHodge/go-octopusdeploy/blob/8b6e9627d5bef8f44f78f72b0013f6cc9d302243/octopusdeploy/variables.go

Edit: I built the provider locally with the changes to go-octopusdeploy's variables.go found in [this gist ](https://gist.github.com/SethNute/ec87a53909beeab1643aa868c2b4e08e) and it appears to fix the issue.

**Comment by AdminTurnedDevOps** [comment]
Get @SethNute, thanks for bringing this up. I'm going to add this to the "features" list. We're getting ready to release a beta and V2 will be where we add the features.
