### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#4]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Monday Nov 05, 2018 at 23:03 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/14_

----

- [ ] Move all documentation into the `/docs/provider/` folder
- [ ] Make sure all documentation matches "Terraform standards"
- [ ] Add to contributing guide that documentation must conform to these standards

**Comment by AdminTurnedDevOps** [comment]
Actively working on this for the beta implementation.
