### ISSUE TITLE
Support all the feed types

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/terraform-provider-octopusdeploy#40]
These are all the feed types in Octopus. This issue to is to track overall progress on supporting these.

- [ ] AwsElasticContainerRegistry
- [ ] BuiltIn
- [ ] Docker
- [ ] GitHub
- [ ] Helm
- [ ] Maven
- [ ] NuGet
- [ ] ~OctopusProject~

**Comment by droyad** [comment]
v1 will just support NuGet at this stage

**Comment by droyad** [comment]
Docker feed should be next. 
BuiltIn would also be good so it can be configured.
The rest lag in adoption, in order GitHub, Helm, AWS, Maven

**Comment by AdminTurnedDevOps** [comment]
We are actively supporting all feed types that the API allows us to use for beta. Each of which can be used in the `feeds` resource and called upon at the time of creation.
