### ISSUE TITLE
Unsupported Resources

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/terraform-provider-octopusdeploy#41]
These are resources available via the API that are currently not supported and do not have a separate issue raised.

# ToDo
We plan to support these sooner or later

## Users, Security and configuration
`ApiKeyResource`
`FeaturesConfigurationResource`
`LicenseResource`
`OctopusServerNodeResource` - Configuration of Task Cap
`ServerConfigurationResource` - Configuration of the ServerUri
`SmtpConfigurationResource`
`TeamResource`
`UpgradeConfigurationResource`
`UserResource`
`UserRoleResource`

## Infrastructure and Project Configuration
`AutoDeployReleaseOverrideResource`
`ProjectTriggerResource`
`ProxyResource`
`SpaceResource`
`SubscriptionResource`
`TagSetResource`
`TenantResource`
`TenantVariableResource`
`WorkerPoolResource`
`WorkerResource`

# Probably Not
It's unlikely we'll add these unless they are requested
`DashboardConfigurationResource`
`InvitationResource`
`LetsEncryptConfigurationResource`
`LoadBalancerPingResource`
`MaintenanceConfigurationResource`
`PerformanceConfigurationResource`

# Won't Add
These are unlikely to be supported

## Deployment
These resources are post-release creation (deployment related), so it's unlikely they would be managed through Terraform

`ArtifactResource`
`DefectResource`
`DeploymentTemplateResource`
`ReleaseTemplateResource`
`InterruptionResource`
`LifecycleProgressionResource`
`PackageResource`
`ReleaseResource`
`TaskResource`

## UI/Interactive
These resources are primarily used to query and then transform the data that exists in Octopus. It's not obvious how these would benefit from being in Terraform

`ActionsUpdateResource`, `ActionUpdateResultResource` - Used in updating of steps based on their template
`ActionTemplateCategoryResource` - List of supported steps to display in the UI
`ActionTemplateSearchResource` - Search for steps
`ActionTemplateUsageResource` - Usage of step templates
`AzureResourceGroupResource`, `AzureStorageAccountResource` - Lists resources in Azure (not Octopus) for UI Selection
`BuiltInFeedStatsResource` - Statistics for the built-in repository
`CertificateUsageResource`, `LibraryVariableSetUsageResource`, - Shows Usage of a resource in Octopus
`CloudTemplateResource` - Provides information to the UI to allow setting of variables based on  HCL, Terraform, CF Templates
`DocumentTypeResource`, `EventAgentResource`, `EventCategoryResource`, `EventGroupResource` - For event filtering
`ExtensionsInfoResource`
`LicenseStatusResource`
`MultiTenancyStatusResource`
`OctopusServerClusterSummaryResource`
`OctopusServerNodeDetailsResource`
`OnboardingResource`
`PackageNotesResult`
`ProgressionResource`
`ReportDeploymentCountOverTimeResource`
`ScheduledTaskDetailsResource`
`SchedulerStatusResource`
`ServerConfigurationSettingsResource` - View of all the settings
`ServerStatusResource`
`ServerTimezoneResource` - Gets the timezone of the server
`SmtpIsConfiguredResource` - Gets the status only
`SystemInfoResource`
`TeamNameResource` - For select lists
`TenantMissingVariablesResource`

## Other
`CommunityActionTemplateResource` - Steps synced from the community library
`DashboardResource`
`EventResource`

**Comment by AdminTurnedDevOps** [comment]
Added this to the features list.

**Comment by AdminTurnedDevOps** [comment]
Added this to a feature list in Trello.
