### ISSUE TITLE
NuGet Feed Resource

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/terraform-provider-octopusdeploy#43]
The current `octopusdeploy_feed` is in the shape required for a `NuGet` feed. We should make it explicit and call it `octopusdeploy_nuget_feed` and split it up so that we can support the other feed types easily.

## Feed Struct
Despite what the resource in the server says, the .NET client [defines](https://github.com/OctopusDeploy/OctopusClients/blob/5381b42cc24065345972a9d2731b4a67c7dd6955/source/Octopus.Client/Model/FeedResource.cs) the base class as just having a `Name`. 

The `FeedType` should be hard coded based on the resource type. It will never change once created.

`SpaceId` 

`List<string> PackageAcquisitionLocationOptions` is for the UI and should be included in the GO client but omitted from the terraform.

## NuGet Feed Struct
https://github.com/OctopusDeploy/OctopusClients/blob/master/source/Octopus.Client/Model/NuGetFeedResource.cs

`int DownloadAttempts`, `int DownloadRetryBackoffSeconds` and `bool EnhancedMode` should be optional and defaulted to `5`, `10` and `false` respectively

`string Username` and `Sensitive Password` are optional (either or both could be `null`).

**Comment by droyad** [comment]
Related to #40

**Comment by AdminTurnedDevOps** [comment]
This resource has been created for the beta provider.
