### ISSUE TITLE
Username Password Account Resource

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/terraform-provider-octopusdeploy#46]
Depends on #45 
https://github.com/OctopusDeploy/OctopusClients/blob/ac5b1baa37c25511d0739a27b451fb453814e5d9/source/Octopus.Client/Model/Accounts/UsernamePasswordAccountResource.cs

- `string Username`
- `Sensitive Password` - Optional (`null`)

![image](https://user-images.githubusercontent.com/1687639/65292300-34df3280-db9a-11e9-8588-a3167e07310b.png)

**Comment by AdminTurnedDevOps** [comment]
This resource has been created in the beta provider.
