### ISSUE TITLE
Implement Better Versioning / Release / Changelog

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#5]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Monday Nov 05, 2018 at 23:11 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/15_

----

To make sure the provider is more stable, the versioning and release process needs to be refined. 

- [ ] Determine when is a good time to start using Semver
- [x] Update AppVeyor to not create a GitHub release on each build
- [ ] Work out an automated way to handle the change log, perhaps [commitizen](https://commitizen.github.io/cz-cli/) or [clog-cli](https://github.com/clog-tool/clog-cli)

**Comment by MattHodge** [comment]
<a href="https://github.com/pbar1"><img src="https://avatars0.githubusercontent.com/u/26949935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pbar1](https://github.com/pbar1)**
_Friday Nov 09, 2018 at 00:00 GMT_

----

[Semantic Release](https://github.com/semantic-release/semantic-release) is an idea, I've had success using it in the past

**Comment by AdminTurnedDevOps** [comment]
This is definitely needed. As the project grows and after beta, we'll need to think about a proper release schedule.
