### ISSUE TITLE
Variable Race condition

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/terraform-provider-octopusdeploy#53]
When there are many variables, the provider will sometimes parallelise the updating of the variable set, which causes some to be missed. There is a bug in the server that does do the version check correctly if there are simultaneous requests.

This will likely not be a problem if we decide to deal with Variable Sets as a resource instead of individual variables.

**Workaround**: Specify the `-parallelism=1` parameter

**Comment by fenneh** [comment]
Is there any way to verify this or do you just happen to notice the server missing variables?

**Comment by droyad** [comment]
You can re-run the apply, which will notice that they are missing. No warnings or anything is printed though. I've added a workaround.
