### ISSUE TITLE
No possibility to set namespace in Kubernetes deployment target 

### ISSUE THREAD

**Issue by jerckov** [OctopusDeploy/terraform-provider-octopusdeploy#55]
**Description**
There is no possibility to set `namespace` field in Kubernetes deployment target. In the [commit](https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/commit/3d2e4d4688598559edb3ac6485638973ae35775d#diff-89dfa9860810ffeeb17f7163673d27dc) we can see that the `namespace` field is available in terraform schema (`resourceMachine()` function) but is ignored afterwards (`buildMachineResource` function).   

**Steps to reproduce**
1.Create file `main.tf` with resource:
```
resource "octopusdeploy_machine" "deployment_target" {
  name             = "foo"
  environments     = [data.octopusdeploy_environment.default.id]
  machinepolicy    = "MachinePolicies-1"
  roles            = ["some-role"]
  isdisabled       = false
  tenanteddeploymentparticipation = "Untenanted"

  endpoint {
    communicationstyle  = "Kubernetes"
    thumbprint          = ""
    uri                 = ""
    clusterurl          = "https://x.x.x.x"
    namespace           = "expected-namespace"
    skiptlsverification = true
    defaultworkerpoolid = "WorkerPools-1"

    authentication      {
        accountid          = "some-token"
        authenticationtype = "KubernetesStandard"
    }
  }
}
```
2. Execute `terraform apply`

**Expected behavior**
Kubernetes deployment target `Namespace` field should be seted

**Comment by AdminTurnedDevOps** [comment]
This has been resolved in (#57)
