### ISSUE TITLE
Improvements to octopusdeploy_lifecycle resource

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#6]
<a href="https://github.com/MattHodge"><img src="https://avatars0.githubusercontent.com/u/1966555?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MattHodge](https://github.com/MattHodge)**
_Tuesday Nov 06, 2018 at 07:04 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/17_

----

- [ ] For `tentacle_retention_policy`, the `unit` should allow lowercase `Days` and `Items`. Currently, if you use lower case you get: `octopusdeploy_lifecycle.foo: "days" is an invalid value for argument tentacle_retention_policy.0.unit. Must be one of []string{"Days", "Items"}`

- [ ] The `octopusdeploy_lifecycle` data source is currently not providing many attributes (only `name`, `description`, and `use_guided_failure`. More attributes should be supported.

**Comment by MattHodge** [comment]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [droyad](https://github.com/droyad)**
_Monday Nov 12, 2018 at 04:07 GMT_

----

`phases` also do not currently support setting the `release_retention_policy` and `tentacle_retention_policy` mainly because I couldn't figure out how to go another level deep in looking up the values

**Comment by AdminTurnedDevOps** [comment]
Added these topics to the features list.
