### ISSUE TITLE
Account - No default set for the required property TenantedDeploymentMode

### ISSUE THREAD

**Issue by ivonin** [OctopusDeploy/terraform-provider-octopusdeploy#65]
**Describe the bug**
Trying to create an account results in an error message, the account doesn't get created in the Octopus Deploy.

**Steps to reproduce**
This simple example does the trick:

```
resource "octopusdeploy_account" "test_account" {
  name         = "Test_Cluster_Token"
  account_type = "Token"
  environments = [
    "Environment-2"
  ]
}

```

**Expected behavior**
I expect the resource to be created 😄 

**Logs and other supporting information**
> Error: error creating account Test_Cluster_Token: cannot get item from endpoint accounts. response from server 500 Internal Server Error

**Screenshots**

**Environment and versions:**
- OS: MacOSX
- Octopus Server Version: 2019.11.3
- Terraform Version: 0.12.20
- Octopus Terraform Provider Version: 0.5.0

**Additional context**
Other resources that I tried to create worked fine and I can create accounts manually, so it's not a problem with Octopus installation or with provider settings.

**Comment by droyad** [comment]
@ivonin Thanks for that. Could you get me the error stack trace on the Octopus Server side? If you go to `Configuration > Diagnostics` under the `Server Logs` section the Internal Server error should be shown.

**Comment by ivonin** [comment]
> @ivonin Thanks for that. Could you get me the error stack trace on the Octopus Server side? If you go to `Configuration > Diagnostics` under the `Server Logs` section the Internal Server error should be shown.

> Unhandled error on request: https://deploy.directcrm.ru/api/accounts 77da6f6f16ea450eafa475047d27a955 by <anonymous> : Error converting value "" to type 'Octopus.Server.Extensibility.HostServices.Model.Tenants.TenantedDeploymentMode'. Path 'TenantedDeploymentParticipation', line 1, position 227. Newtonsoft.Json.JsonSerializationException: Error converting value "" to type 'Octopus.Server.Extensibility.HostServices.Model.Tenants.TenantedDeploymentMode'. Path 'TenantedDeploymentParticipation', line 1, position 227. ---> System.ArgumentException: Must specify valid information for parsing in the string.
>    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Octopus.Core.Serialization.InheritedClassConverter`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Core\Serialization\InheritedClassConverter.cs:line 89
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Octopus.Server.Web.Infrastructure.Api.ModelBinder.Bind(Type type) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\Api\IModelBinder.cs:line 60
>    at Octopus.Server.Web.Infrastructure.Api.ModelBinder.BindAndValidate(Type type) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\Api\IModelBinder.cs:line 70
>    at Octopus.Server.Web.Infrastructure.Api.ModelBinderExtensions.BindAndValidate[TModel](IModelBinder modelBinder) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\Api\IModelBinder.cs:line 27
>    at Octopus.Server.Web.Infrastructure.Api.CustomCreateResponder`3.ExecuteRegistered() in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\Api\CustomCreateResponder.cs:line 42
>    at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\Api\Responder.cs:line 52
>    at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object o, CancellationToken x) in C:\buildAgent\work\abb2fbfce959a439\source\Octopus.Server\Web\Infrastructure\OctopusNancyModule.cs:line 125
>    at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()

The log does make it pretty clear on how to work around the issue, thanks. I'll try to fix my resource declaration.

**Comment by droyad** [comment]
@ivonin Awesome, thanks.

Note to whoever picks this up, we have the property, just need to default it to `Untenanted` when not supplied

**Comment by AdminTurnedDevOps** [comment]
This has been fixed for the beta provider.
