### ISSUE TITLE
Settings namespace for kubernetes endpoint has no effect

### ISSUE THREAD

**Issue by ivonin** [OctopusDeploy/terraform-provider-octopusdeploy#66]
**Describe the bug**
The field `endpoint.namespace` in the machine resource doesn't seem to affect the actual value of "namespace" field on the deployment target.

**Steps to reproduce**

- Apply the resource definition below.
- Check the deployment target in the Octopus UI

```
resource "octopusdeploy_machine" "deployment_targets" {

  name                            = "Test"
  machinepolicy                   = data.octopusdeploy_machinepolicy.default.id
  tenanteddeploymentparticipation = "TenantedOrUntenanted"
  isdisabled                      = false

  endpoint {
    communicationstyle = "Kubernetes"
    thumbprint         = random_string.endpoint_thumbprint.result

    uri        = "..."
    clusterurl = "..."
    skiptlsverification = true
    namespace           = "myapp"

    authentication {
      accountid          = "Account-1"
      authenticationtype = "KubernetesStandard"
    }
  }

  environments = [
    "Environment-1"
  ]

  roles = [
    "role1"
  ]
}
```

**Expected behavior**
The kubernetes namespace should be set to "myapp"

**Logs and other supporting information**

Apply output (the relevant part):

```
      + endpoint {
          + clusterurl          = "https://.../"
          + communicationstyle  = "Kubernetes"
          + namespace           = "myapp"
          + skiptlsverification = true
          + thumbprint          = "0Flxck4hM8VHepMvK38jvrgE"
          + uri                 = "https://.../"

          + authentication {
              + accountid          = "Account-1"
              + authenticationtype = "KubernetesStandard"
            }
        }
```

**Environment and versions:**
- OS: MacOSX
- Octopus Server Version: 2019.11.3
- Terraform Version: 0.12.20
- Octopus Terraform Provider Version: 0.5.0

**Additional context**
Neither creating nor updating the machine works as expected.

**Comment by ivonin** [comment]
Looking at [resource_machine.go](https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/3e7447833306e599fd28464678843eec2d598414/octopusdeploy/resource_machine.go), it doesn't seem like the "namespace" value is ever used to do something

**Comment by ivonin** [comment]
I was pointed to #57 by a colleague whilch seems to solve exactly my problem... Any news on that?

**Comment by AdminTurnedDevOps** [comment]
Per issue #57, this has been resolved. The namespace is now part of the resource creation and build process.

`tfMachine.Endpoint.Namespace = tfSchemaList["namespace"].(string)`
