### ISSUE TITLE
Scale support for Deployment Step Templates

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#7]
<a href="https://github.com/pbar1"><img src="https://avatars0.githubusercontent.com/u/26949935?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pbar1](https://github.com/pbar1)**
_Friday Nov 09, 2018 at 00:43 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/19_

----

There are a great many official deployment step templates, as seen here.
![image](https://user-images.githubusercontent.com/26949935/48235799-f9be8100-e384-11e8-90d3-1850561410d4.png)

The provider currently has support for the main ones (like IIS deployments) through a named map block, which doesn't seem like it would scale well. Does creating either of the following sound logical enough?
- An `octopusdeploy_deployment_step` resource 
- An `octopusdeploy_deployment_step_template` data provider that can generate the step (akin to the `aws_iam_policy_document` data provider that has a JSON document as an attribute)

**Comment by MattHodge** [comment]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [droyad](https://github.com/droyad)**
_Monday Nov 12, 2018 at 04:28 GMT_

----

I am currently working on this generic `octopusdeploy_deployment_step` resource. It currently looks something like this:
```
resource "octopusdeploy_deployment_process" "test''" {
            project_id = "${octopusdeploy_project.test.id}"

            step {
                name = "Test"

                action {
                    name = "Test"
                    action_type = "Octopus.Script"

                    property {
                        key = "Octopus.Action.RunOnServer"
                        value = "true"
                    }
                }
            }
        }
```

**Comment by MattHodge** [comment]
<a href="https://github.com/pbar1"><img src="https://avatars0.githubusercontent.com/u/26949935?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pbar1](https://github.com/pbar1)**
_Friday Nov 16, 2018 at 23:12 GMT_

----

Awesome, that kinda reminds me of the Helm provider for Terraform, which has a similar challenge (lots and lots of possible keys/values)

**Comment by AdminTurnedDevOps** [comment]
The `deploy_step` resource now exists.
