### ISSUE TITLE
Error: missing provider "octopusdeploy"

### ISSUE THREAD

**Issue by woodyj56** [OctopusDeploy/terraform-provider-octopusdeploy#73]
I am trying to get the plugin provider working locally however when i run terraform init i get the following error

c:\octopus>terraform init -plugin-dir=c:\octopus\terraform.d\plugins\windows_amd64

Initializing the backend...

Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* octopusdeploy (any version)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/windows_amd64

Error: missing provider "octopusdeploy"

**Steps to reproduce**
1) download and extract the latest plugin 0.5.0 and the latest terraform binary (0.12.28) to c:\octopus
2) copy the plugin into c:\octopus\terraform.d\plugins\windows_amd64
3) from the cmdline run terraform init -plugin-dir c:\octopus\terraform.d\plugins\windows_amd64
**Expected behaviour**
terraform to initialise without error

**Environment and versions:**
- OS: Windows
- Terraform Version: 0.12.28
- Octopus Terraform Provider Version: 0.5.0

**Comment by droyad** [comment]
Try copying the plugin into the same folder as your terraform files

**Comment by woodyj56** [comment]
hey, thanks for the response.  I get the same error unfortunately

**Comment by ScottGuymer** [comment]
The plugin will need to be names `terraform-provider-octopusdeploy` (probably with .exe on windows) if you put it in the same folder as your tf files.

**Comment by AdminTurnedDevOps** [comment]
Hey @woodyj56 

You'll need to copy the plugin into the exact directory where the Terraform configurations. It needs to be in the specific directory associated with your OS version. For example, on MacOS, I would put the plugin in:

`.terraform/plugins/darwin_amd64`

Screenshot below.
![2020-08-18_11-43-32](https://user-images.githubusercontent.com/28905827/90534703-0c640d80-e148-11ea-8902-77c332b7a2a0.png)
