### ISSUE TITLE
Sensitive variable support

### ISSUE THREAD

**Issue by MattHodge** [OctopusDeploy/terraform-provider-octopusdeploy#8]
<a href="https://github.com/droyad"><img src="https://avatars0.githubusercontent.com/u/1687639?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [droyad](https://github.com/droyad)**
_Monday Nov 12, 2018 at 04:41 GMT_
_Originally opened as https://github.com/MattHodge/terraform-provider-octopusdeploy/issues/20_

----

While we can add support to Octopus for sensitive variables (see https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/35616472-provide-a-hash-of-sensitive-variables-so-we-can-de), it would meant that users on older versions can't use this provider with sensitive variables unless we have some fallback.

The other providers (eg Azure) I've used take the approach of storing the value in the state and only updating if the new value is different from the state, ignoring what the actual value is due to it not being retrievable.

Those other providers unfortunately store the secret in plain text in the state :(.

**Comment by jeff-french** [comment]
Basic support implemented in #24 and enhanced support captured in #23
