### ISSUE TITLE
Query: octopusdeploy_machine resource - proxyid

### ISSUE THREAD

**Issue by elandmancrs** [OctopusDeploy/terraform-provider-octopusdeploy#92]
Hi all, 

Need a little help please. This is part of my declaration in my main.tf...

```
resource "octopusdeploy_machine" "Tentacle" {
    environments = ["${octopusdeploy_environment.AZRStaging2.id}"]
    name = "APP (##.##.##.##)"
    tenanteddeploymentparticipation = "Untenanted"
    isdisabled = "false"
    machinepolicy = "MachinePolicies-1"
    roles = ["APP", "Website"]
  endpoint {
    communicationstyle = "TentaclePassive"
    thumbprint = "####################################"
    uri = "https://##.##.##.##:10933"
    proxyid = null
  }
}
```
Running this results in the machine being unhealthy. 
In the Events tab of the tentacle, the unhealthy tentacle's json its referenced as `"ProxyId": "",`. 
Plus the error thrown in the unhealthy event is "Proxy  not found in the database"

A healthy tentacle's json reports back as `"ProxyId": null,` with no error about proxy not being in database.

I've tried using ....
proxyid = null
proxyid = ""
...and leaving it out completely.
The same results...

Am I referencing the proxyid incorrectly?

**Comment by elandmancrs** [comment]
@AdminTurnedDevOps, have you managed to look at this query? :)
Thanking you kindly

**Comment by AdminTurnedDevOps** [comment]
Hey @elandmancrs 

At the moment we're pushing a ton of new changes and getting the provider ready for beta, so please bear with us for a little while longer. Some of the changes we're pushing may fix this as well. 

Once we're officially good to go, I'll let you know here.

**Comment by elandmancrs** [comment]
That's great. This plugin will save my life!
Thank you

**Comment by jbristowe** [comment]
Hey @elandmancrs! This has been fixed in `beta-candidate-01` (soon to be merged). The definition for `octopusdeploy_machine` has been made more explicit in `beta-candidate-01`. Your example (above)now looks like this:

```terraform
resource "octopusdeploy_listening_tentacle_deployment_target" "listening_tentacle" {
  environments                      = [octopusdeploy_environment.AZRStaging2.id]
  machine_policy_id                 = "MachinePolicies-1"
  name                              = "APP (##.##.##.##)"
  proxy_id                          = "Proxys-123"
  roles                             = ["APP", "Website"]
  tenanted_deployment_participation = "Untenanted"
  tentacle_url                      = "https://##.##.##.##:10933"
  thumbprint                        = "####################################"
}
```

The thinking (here) was to make deployment targets more explicit in their definition. That way, you're not adding any conflicting properties that are shared across machine types (AKA, deployment targets).

Also, I added the data source, `octopusdeploy_listening_tentacle_deployment_targets`, which allows you to query for listening tentacles via a number of filters:

```terraform
data "octopusdeploy_listening_tentacle_deployment_targets" "listening_tentacle_deployment_targets" {
  # deployment_id   = "Deployments-123"
  # environments    = ["Environments-123", "Environments-321"]
  # health_statuses = ["HasWarnings"]
  # ids             = ["Machines-123", "Machines-321"]
  # is_disabled     = false
  # name            = "Listening Tentacle (OK to Delete)"
  # partial_name    = "Listening Tentac"
  # roles           = ["Roles-123", "Roles-321"]
  # shell_names     = []
  # skip            = 5
  # take            = 100
  # tenant_tags     = []
  # tenants         = []
  # thumbprint      = ""
}
```
