### ISSUE TITLE
Support for Resource-Level and Field-Level Descriptions

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/terraform-provider-octopusdeploy#99]
From the [Terraform Plugin SDK v2 Upgrade Guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html):

>The `helper/schema.Resource` and `helper/schema.Schema` types both now have `Description` properties that accept strings. These properties are laying the groundwork for future improvements to Terraform, and will have no visible effect to the Terraform CLI at the moment. If you’d like to build in support for your provider starting now, it’s recommended that you set these properties to whatever you’d document the resource or field as in your terraform.io docs for the resource.
>
>You can globally set the format of the text in these fields by setting the global variable `helper/schema.DescriptionKind`. Its acceptable values are `helper/schema.StringPlain` (plain text, the default) or `helper/schema.StringMarkdown` (markdown formatting).

More information is available on [Support for Resource-Level and Field-Level Descriptions](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-resource-level-and-field-level-descriptions).

**Comment by jbristowe** [comment]
A few things come to mind, @AdminTurnedDevOps:

- Are there any recommendations from HashiCorp for these descriptions? For example, is there any best practices? What's the maximum length?
- How will these descriptions be used by consumers of our provider?
- I recommend that we persist these as string constants.

**Comment by AdminTurnedDevOps** [comment]
As of right now, I'm not seeing any "best practices" per-say in the docs, but I'll see if there is anything else lying around on the web. This is the closest I would see to a best practice:

"If you’d like to build in support for your provider starting now, it’s recommended that you set these properties to whatever you’d document the resource or field as in your terraform.io docs for the resource."

The descriptions themselves wouldn't be used directly by a consumer of the provider. They're more like internal documentation for us. It's like writing documentation directly in the code, or using comments.

Yeah! We can definitely turn these into constants. Perhaps a separate constants file purely for descriptions?

**Comment by AdminTurnedDevOps** [comment]
Added in constants for the descriptions and added in the descriptions: https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/commit/7cd56e7252568461afad9a0232a96c692d41c1b5

**Comment by jbristowe** [comment]
Implemented across data sources and resources. 👍
